config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do 
    resources :tools, only: [:index, :show]
  end

  namespace :admin do 
    resources :tools, except: [:show]
    # resources :users, only: [:index, :show]
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tools, dependent: :destroy
  validates :username, presence: true, 
                       uniqueness: true
  enum role: %w(default admin) 
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::BaseController
  before_action :set_tool, only: [:edit, :update, :destroy]

  def index
    @tools = Tool.all
  end

  def show
  end

  def edit
  end

  def update
    @tool.update(tool_params)
    redirect_to admin_tools_path
  end 

  def new
    @tool = Tool.new
  end 

  def create
  @tool = Tool.create(tool_params) 
    if @tool.save
      redirect_to admin_tools_path
      flash[:notice] = "You've succesfully created a new tool"
    else 
      render :new
    end
  end 

  def destroy
    @tool.destroy

    redirect_to admin_tools_path
  end 

  private

  def tool_params
    params.require(:tool).permit(:name, :use, :user_id)
  end

  def set_tool
    @tool = Tool.find(params[:id])
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool
  helper_method :current_user 
  before_action :initiate_session
  #see set tool method
  def most_recent_tool
      Tool.find_by(id: session[:most_recent_tool_id])
  end 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 
  
  def initiate_session #moved to application_controller
      session[:most_recent_tool_id]  = Tool.all.last.id 
  end

  def current_admin?
    current_user && current_user.admin? #enum role: %w(default admin) in User Model
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end 

  def create
    user = User.find_by(username: params[:session][:username]) 
    if user
      user && user.authenticate(params[:session][:username])
      session[:user_id] = user.id
      flash[:notice] = "Welcome Back!"
      redirect_to user_path(user)
    else
      flash[:notice] = "Unsuccesful Login"
      redirect_to login_path
    end 
  end 

  def destroy
    session.clear
    redirect_to login_path
    flash[:notice] = "Logged Out!"
  end 
end 

app/controllers/tools_controller.rb
class ToolsController < ApplicationController #looks for tools folder in app views, and index file
  before_action :set_tool, only: [:show] #only: [:show, :edit, :update, :destroy] 
  before_action :set_user, only: [:index]    #to refactor @tool.find(params[:id])
  # before_action :initiate_session #moved to application_controller

  def index
    @tools = @user.tools.all
    flash[:Milwaukee] = "This page is brought to you by Milwaukee Power Tools."
    # session[:most_recent_tool_id] = Tool.all.last.id
    # @tools = Tool.all
  end 

  def show
    # @tool = Tool.find(params[:id])
  end

  private

  def set_tool 
    @tool = Tool.find(params[:id])
  end 

  def set_user
    @user = current_user
    # @user = User.find(params[:user_id])
  end 

  def tool_params
    params.require(:tool).permit(:name, :use)
  end

  # def new
  #   @tool = @user.tools.new
  # end 

  # def create
  #   @tool = @user.tools.create(tool_params) 
  #     if @tool.save
  #       redirect_to user_tools_path
  #       flash[:notice] = "You've succesfully created a new tool"
  #     else 
  #       render :new
  #     end
  # end 

  # def edit
  #   # @tool = Tool.find(params[:id])
  # end 

  # def update
  #   # @tool = Tool.find(params[:id])
  #   @tool.update(tool_params)

  #   redirect_to user_tools_path
  # end 

  # def destroy
  #   # @tool = Tool.find(params[:id])
  #   @tool.destroy

  #   redirect_to user_tools_path
  # end 


  # def initiate_session #moved to application_controller
  #   session[:most_recent_tool_id]  = Tool.all.last.id
  # end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Account Created!" 
      redirect_to @user
    else
      flash[:notice] = "Invalid Account!"
      redirect_to new_user_path
    end
  end

  def show
    session[:hit_counter] = session[:hit_counter].to_i + 1
    @user = current_user
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/tools/_form.html.erb
<%= form_for(@tool, url: target) do |f| %>
  <%= f.label "name:" %> 
  <%= f.text_field :name %>
  <br>

  <%= f.label "use:" %> 
  <%= f.text_field :use %>
  <br>

  <%= f.label "user_id:" %> 
  <%= f.text_field :user_id %>
  <br>

  <%= f.submit %> 
<%end%>

app/views/admin/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= form_for(@tool, url: admin_tool_path(@tool.id)) do |f| %>
  <%= f.label "name:" %> 
  <%= f.text_field :name %>
  <br>

  <%= f.label "use:" %> 
  <%= f.text_field :use %>
  <br>

  <%= f.label "user_id:" %> 
  <%= f.text_field :user_id %>
  <br>

  <%= f.submit %> 
<%end%>

app/views/admin/tools/index.html.erb
<h1>Tools Index</h1>

<%= link_to "New tool", new_admin_tool_path %>

<% @tools.each do |tool| %>
  <h3><%= tool.name %></h3>
  <h5><%= tool.use %></h5>
  <%= link_to "edit", edit_admin_tool_path(tool.id) %>
  <%= link_to "delete", admin_tool_path(tool.id), method: :delete %>
<%end%>

app/views/admin/tools/new.html.erb
<h1>Create New Tool</h1>

<%= form_for(@tool, url: admin_tools_path) do |f| %>
  
  <%= f.label "name:" %> 
  <%= f.text_field :name %>
  <br>

  <%= f.label "use:" %> 
  <%= f.text_field :use %>
  <br>

  <%= f.label "user_id:" %> 
  <%= f.text_field :user_id %>
  <br>

  <%#= f.hidden_field user_id: %> 

  <%= f.submit %> 
<%end%>

app/views/admin/tools/show.html.erb
<h1><%=@tool.name%></h1>
<h3><%=@tool.use%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p>
   <strong>Newest tool:</strong> <%= most_recent_tool.name %>
  </p>

  <% flash.each do |type, message| %> 
    <%= content_tag(:div, message, class: "flash_#{type}") %>
  <%end%>

  <% if current_user %> 
      <%= link_to "Logout", logout_path, method: :delete %> 
  <% end %> 
  
  <%= yield %>

</body>
</html>

app/views/tools/index.html.erb
<h1>All Tools</h1>

<% current_user.tools.each do |tool| %>
  <p><h3><%=link_to(tool.name, user_tool_path(current_user, tool.id)) %></h3> <h5> (<%= tool.use %>) </h5>
<%end%>

app/views/tools/show.html.erb
<h1><%=@tool.name%></h1>
<h3><%=@tool.use%></h3>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<%= form_for(@user) do |f| %> 
  <%= f.label :username %> 
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %> 
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %> 
  <%= f.password_field :password_confirmation %>
  <br>
 
  <%= f.submit "Create Account" %>
<% end %> 

app/views/users/show.html.erb
<p> Visits: <%= session[:hit_counter] %>

<h1>Welcome <%= @user.username %>! </h1>

<%= link_to "tool index", user_tools_path(@user) %>